---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wp-cm
   labels:
      app: wordpress
data:                     
   WORDPRESS_DB_HOST: wpdb-cluster-mysql-master
   WORDPRESS_DB_NAME: wpdb
   WORDPRESS_DB_USER: root