---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: wp-pvc
   labels:
      app: wordpress
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
   storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: wp-deploy
   labels:
      app: wordpress
spec:
   replicas: 1
   selector:
      matchLabels:
         app: wp-pod
   template:
      metadata:
         name: wp-pod
         labels:
            app: wp-pod
      spec:
         volumes:
         -  name: wp-vol
            persistentVolumeClaim:
               claimName: wp-pvc
         containers:
         -  name: wp-container
            image: wordpress
            imagePullPolicy: IfNotPresent
            envFrom:
            -  configMapRef: 
                  name: wp-cm
            - secretRef:
                  name: wp-secret
            ports:
            -  name: wp-port
               containerPort: 80
            volumeMounts:
            -  name: wp-vol
               mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
   name: wp-svc
   labels:
      app: wordpress
spec:
   type: ClusterIP
   selector:
      app: wp-pod
   ports:
   -  name: http-port
      port: 80
      targetPort: wp-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: wp-ing
   labels:
      name: wp-ing
      app: wordpress
   annotations:
     nginx.ingress.kubernetes.io/limit-connections: "10"
spec:
   ingressClassName: nginx
   rules:
   -  host: "fbo-wp.144.126.243.120.nip.io"
      http:
         paths:
         -  path: /
            pathType: Prefix
            backend:
               service:
                  name: wp-svc
                  port:
                     name: http-port